name: chatify
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.3
  file_picker: ^8.0.3
  file_picker_writable: ^2.1.0+1
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  firebase_storage: ^11.7.5
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^6.0.0
  flutter_spinkit: ^5.2.1
  get_it: ^7.7.0
  provider: ^6.1.2
  timeago: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
