// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEncFkrFbVcPMyXimcFkzNwHlc8IliVcI',
    appId: '1:831540079320:web:22961d2f2add42c8ca45ad',
    messagingSenderId: '831540079320',
    projectId: 'chatify-e712d',
    authDomain: 'chatify-e712d.firebaseapp.com',
    storageBucket: 'chatify-e712d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYpHGhmFAQ_7Z8QSR432TAPz_KaJYr980',
    appId: '1:831540079320:android:a29983eb6f134488ca45ad',
    messagingSenderId: '831540079320',
    projectId: 'chatify-e712d',
    storageBucket: 'chatify-e712d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjUj1K_eN4Bc2Tr_h6hDOQi2kFKXARmwA',
    appId: '1:831540079320:ios:50d0d97a157b5b25ca45ad',
    messagingSenderId: '831540079320',
    projectId: 'chatify-e712d',
    storageBucket: 'chatify-e712d.appspot.com',
    iosBundleId: 'com.example.chatify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjUj1K_eN4Bc2Tr_h6hDOQi2kFKXARmwA',
    appId: '1:831540079320:ios:f08eb1e2d9a149dbca45ad',
    messagingSenderId: '831540079320',
    projectId: 'chatify-e712d',
    storageBucket: 'chatify-e712d.appspot.com',
    iosBundleId: 'com.example.chatify.RunnerTests',
  );
}
